version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:22.14.0
    resource_class: medium

workflows:
  version: 2.1
  main:
    jobs:
      - lint
      - test-v8
      - test-v9
      - release:
          requires:
            - lint
            - test-v8
            - test-v9
          filters:
            branches:
              only:
                - master

jobs:
  lint:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Show ESLint version
          command: npx eslint --version
      - run:
          name: Lint code
          command: npm run lint

  test-v8:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install ESLint 8
          command: npm install eslint@8
      - run:
          name: Show ESLint version
          command: npx eslint --version
      - run:
          name: Test ESLint 8
          command: npm run test:legacy

  test-v9:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install ESLint 9
          command: npm install eslint@9
      - run:
          name: Show ESLint version
          command: npx eslint --version
      - run:
          name: Test ESLint 9
          command: npm test

  release:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run semantic release
          command: npm run semantic-release
